[[news]]
date = "2026-07-17"
content = "在中國物理學會高能物理分會第十二屆全國會員代表大會暨學術年會（廣州）作分會報告，題目為“粲介子單舉半輕衰變的唯象學研究”。"

[[news]]
date = "2026-06-09"
content = "論文《Bayesian Extraction of HQET Parameters from Inclusive Semi-Leptonic Decay of the Lambda_c+ Baryon》發表於 Chinese Physics C。"

[[news]]
date = "2026-04-27"
content = "在第八屆全國重味物理與量子色動力學研討會（重慶）作分會報告，題目為“粲強子單舉衰變的唯象學研究”。"

[[news]]
date = "2025-11-23"
content = "在第七屆 Future Tau Charm Facilities 國際研討會（安徽黃山）作口頭報告，題目為 “D meson inclusive decays”。"

[[news]]
date = "2025-10-10"
content = "在重味強子結構專題研討會（江蘇徐州）作口頭報告，題目為“粲強子單舉衰變唯象學研究”。"

[[news]]
date = "2025-09-17"
content = "論文《Data determination of HQET parameters in inclusive charm decays》發表於 Eur. Phys. J. C。"

[[news]]
date = "2025-08-05"
content = "在 2025 年 BESIII 粲強子物理研討會上作口頭報告，題目為“粲介子半輕子單舉衰變的唯象研究”。"

[[news]]
date = "2025-07-18"
content = "在 2025 年重味物理高精度計算研討會（江蘇淮安）作口頭報告，題目為“粲介子半輕子單舉衰變的唯象研究”。"

[[news]]
date = "2024-11-30"
content = "在第二屆武漢高能物理青年論壇作口頭報告，題目為 “Charm inclusive decay”。"

[[news]]
date = "2024-10-25"
content = "在 HFCPV 2024（湖南衡陽）作大會報告，題目為 “Charm Semi-Leptonic Inclusive Decay”。"

[[news]]
date = "2022-11-01"
content = "論文《Inclusive weak-annihilation decays and lifetimes of beauty-charmed baryons》發表於 Physical Review D。"
