[[news]]
date = "2025-09-17"
content = "Published the paper \"Data determination of HQET parameters in inclusive charm decays\" in Eur. Phys. J. C."

[[news]]
date = "2025-08"
content = "Delivered a talk at the 2025 BESIII Charm Hadron Physics Workshop."

[[news]]
date = "2024-11"
content = "Gave a talk at the 2nd Wuhan Youth Forum on High Energy Physics."

[[news]]
date = "2024-10"
content = "Delivered a plenary presentation at HFCPV 2024 on charm semi-leptonic inclusive decay."

[[news]]
date = "2022-11-01"
content = "Published \"Inclusive weak-annihilation decays and lifetimes of beauty-charmed baryons\" in Physical Review D."
