[[news]]
date = "2025-11-23"
content = "Delivered an oral presentation \"D meson inclusive decays\" at The 7th International Workshop on Future Tau Charm Facilities in Huangshan."

[[news]]
date = "2025-10-10"
content = "Delivered an oral presentation \"Phenomenological study of inclusive charm-hadron decays\" at the Workshop on the Structure of Heavy-flavor Hadrons in Xuzhou."

[[news]]
date = "2025-09-17"
content = "Published the paper \"Data determination of HQET parameters in inclusive charm decays\" in Eur. Phys. J. C."

[[news]]
date = "2025-08-05"
content = "Delivered an oral presentation \"Phenomenological study on semi-leptonic inclusive decay of charm meson\" at the 2025 BESIII Charm Hadron Physics Workshop."

[[news]]
date = "2025-07-18"
content = "Delivered an oral presentation \"Phenomenological study on semi-leptonic inclusive decay of charm meson\" at the Workshop on High-precision Heavy-flavor Physics in Huai'an."

[[news]]
date = "2024-11-30"
content = "Delivered an oral presentation \"Charm inclusive decay\" at the 2nd Wuhan Youth Forum on High Energy Physics."

[[news]]
date = "2024-10-25"
content = "Delivered a plenary presentation \"Charm Semi-Leptonic Inclusive Decay\" at HFCPV 2024 in Hengyang."

[[news]]
date = "2022-11-01"
content = "Published \"Inclusive weak-annihilation decays and lifetimes of beauty-charmed baryons\" in Physical Review D."
