[[news]]
date = "2025-11-23"
content = "在第七届 Future Tau Charm Facilities 国际研讨会（安徽黄山）作口头报告，题目为 “D meson inclusive decays”。"

[[news]]
date = "2025-10-10"
content = "在重味强子结构专题研讨会（江苏徐州）作口头报告，题目为“粲强子单举衰变唯象学研究”。"

[[news]]
date = "2025-09-17"
content = "论文《Data determination of HQET parameters in inclusive charm decays》发表于 Eur. Phys. J. C。"

[[news]]
date = "2025-08-05"
content = "在 2025 年 BESIII 粲强子物理研讨会上作口头报告，题目为“粲介子半轻子单举衰变的唯象研究”。"

[[news]]
date = "2025-07-18"
content = "在 2025 年重味物理高精度计算研讨会（江苏淮安）作口头报告，题目为“粲介子半轻子单举衰变的唯象研究”。"

[[news]]
date = "2024-11-30"
content = "在第二届武汉高能物理青年论坛作口头报告，题目为 “Charm inclusive decay”。"

[[news]]
date = "2024-10-25"
content = "在 HFCPV 2024（湖南衡阳）作大会报告，题目为 “Charm Semi-Leptonic Inclusive Decay”。"

[[news]]
date = "2022-11-01"
content = "论文《Inclusive weak-annihilation decays and lifetimes of beauty-charmed baryons》发表于 Physical Review D。"
