[[news]]
date = "2025-09-17"
content = "论文《Data determination of HQET parameters in inclusive charm decays》发表于 Eur. Phys. J. C。"

[[news]]
date = "2025-08"
content = "在 2025 年 BESIII 粲强子物理研讨会上作报告。"

[[news]]
date = "2024-11"
content = "在第二届武汉高能物理青年论坛作报告。"

[[news]]
date = "2024-10"
content = "在 HFCPV 2024 作大会报告，主题为 charm semi-leptonic inclusive decay。"

[[news]]
date = "2022-11-01"
content = "论文《Inclusive weak-annihilation decays and lifetimes of beauty-charmed baryons》发表于 Physical Review D。"
